export const textStyles = {
  h1: {
    fontSize: ["48px", "72px"],
    fontWeight: "bold",
    lineHeight: "110%",
    letterSpacing: "-2%",
  },
  h2: {
    fontSize: ["36px", "48px"],
    fontWeight: "semibold",
    lineHeight: "110%",
    letterSpacing: "-1%",
  },
  Titr: {
    fontSize: ["1.25rem", "1.75rem"],
    fontWeight: "semibold",
    lineHeight: "110%",
    letterSpacing: "-1%",
    color: "Black",
    marginBottom: "30px",
    marginTop: "10px",
  },
  TitrColorFul: {
    fontSize: ["1.25rem", "1.75rem"],
    fontWeight: "semibold",
    lineHeight: "110%",
    letterSpacing: "-1%",
    color: "FirstColor",
    marginBottom: "30px",
    marginTop: "10px",
  },
  SpecialTitr: {
    fontSize: ["1.25rem", "1.75rem"],
    fontWeight: "semibold",
    lineHeight: "110%",
    letterSpacing: "-1%",
    color: "FirstColor",
    marginBottom: "30px",
    marginTop: "10px",
    background: "#edf2f754",
    padding: "10px 20px",
    width: "fit-content",
    borderRadius: "5px",
    borderLeft: "3px solid #7d99b5",
  },
  Price :{
    fontSize: ["20px", "24px"],
    color:"red",
    fontWeight: "semibold",
    margin: "10px 0",
  },
  p: {
    fontSize: ["14px", "16px"],
    lineHeight: "160%",
  },
};
